package Enum;

public enum GuessResult {
    SQUARE, THREE_SHOTS_ZERO_FLY, TWO_SHOTS_ONE_FLY, ONE_SHOT_TWO_FLY, ONE_SHOT_ONE_FLY, ZERO_SHOTS_ONE_FLY,
    ONE_SHOT_ZERO_FLY, ZERO_SHOTS_ZERO_FLY, TWO_SHOTS_ZERO_FLY, ZERO_SHOTS_TWO_FLY
}
