package Enum;

public enum MessageType {
    PLAYER_REGISTER,
    PLAYER_REGISTER_FAILED_NAME_ALREADY_USED,
    GUESS,
    READY_CHOICE_GAME_MODE,
    CHOICE_GAME_MODE,
    CHOICE_GAME_MODE_SUCCESS,
    YOUR_TURN,
    INIT_GAME,
    YOU_WIN,
    RESULT,
    ON_LOBBY,
    MATCH_FOUND,
    OPPONENT_TURN,
    OPPONENT_WIN,
    PLAYER_REGISTER_SUCCESS

}
