package Enum;

public enum MessageType {
    PLAYER_REGISTER,
    PLAYER_REGISTER_SUCCESS,
    PLAYER_REGISTER_FAILED_NAME_ALREADY_USED,
    GUESS,
    GUESS_FAILED,
    ON_THE_FLY,
    GAME_FOUND,
    CHOICE_GAME_MODE,
    CHOICE_GAME_MODE_SUCCESS,
    YOUR_TURN,
    GAME_WIN,

}
